
spring.data.mongodb.uri: mongodb://shubham:admin123@tweeterappdb.cluster-cdkavv6oimcc.us-east-1.docdb.amazonaws.com:27017/tweetappdb?replicaSet=rs0&readPreference=secondaryPreferred&retryWrites=false
server:
  port : 5000
